### PR TITLE
extend the asynchttp library to make it more flexible

### PR DESCRIPTION
**Pull request by phlogistonjohn**
Extend the asynchttp lib, mostly around specifying/generating IDs, such that users of the library have more control over it.

### CODE REVIEW

**Comment by phlogistonjohn** [comment]
@obnoxxx , @raghavendra-talur  : In case you aren't monitoring this repo, it looks like the travis job is failing due to the travis stuff not being kept up to date (wrt to go versions & what we're doing in the main heketi repo). I could just try pushing an additional change that pairs this with Go versions that Heketi is using, but I still don't know if anyone on older versions of Go expect to use this lib. Any opinions?

**Review by raghavendra-talur — APPROVED** [review]

**Comment by raghavendra-talur** [comment]
@phlogistonjohn Let us increment the go version in travis.yml as you have suggested and merge this patch :)

**Comment by phlogistonjohn** [comment]
@raghavendra-talur  done. Travis build has now passed.

**Review by obnoxxx — APPROVED** [review]
LGTM, nice patchset!

**Pull request merged**
